default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: timecard_app_development

test:
  <<: *default
  database: timecard_app_test

production:
  <<: *default
  database: timecard_app_production
  username: timecard_app
  password: <%= ENV['TIMECARD_APP_DATABASE_PASSWORD'] %>